# Generated by Django 3.1.2 on 2020-10-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201029_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_required',
            old_name='identity',
            new_name='board_required_identity',
        ),
        migrations.RenameField(
            model_name='button_required',
            old_name='identity',
            new_name='button_required_identity',
        ),
    ]
